[build]
  publish = "dist"

# Direct connection to Render backend endpoints
[[redirects]]
  from = "/api/*"
  to = "https://klassconnect-backend.onrender.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Max-Age = "86400"

# Special handler for OPTIONS preflight requests (Needed for CORS)
[[redirects]]
  from = "/api/*"
  to = "https://klassconnect-backend.onrender.com/:splat"
  status = 204
  force = true
  conditions = {Methods = ["OPTIONS"]}
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Max-Age = "86400"

# Ensure these specific endpoints are properly handled
[[redirects]]
  from = "/api/status"
  to = "https://klassconnect-backend.onrender.com/status"
  status = 200
  force = true

[[redirects]]
  from = "/api/upload"
  to = "https://klassconnect-backend.onrender.com/upload"
  status = 200
  force = true

[[redirects]]
  from = "/api/submit_quiz"
  to = "https://klassconnect-backend.onrender.com/submit_quiz"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for all responses
[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    # Remove this as it might cause issues
    # Content-Security-Policy = "upgrade-insecure-requests"
    # Always allow CORS from any origin
    Access-Control-Allow-Origin = "*"
