[build]
  publish = "dist"

# Improved redirect configuration for all backend endpoints
[[redirects]]
  from = "/api/*"
  to = "https://klassconnect-backend.onrender.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
    Access-Control-Allow-Headers = "*"

# Handle OPTIONS preflight requests for CORS
[[redirects]]
  from = "/*"
  to = "https://klassconnect-backend.onrender.com/:splat"
  status = 200
  force = true
  conditions = {Methods = ["OPTIONS"]}
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
    Access-Control-Allow-Headers = "*"
    Access-Control-Max-Age = "86400"

# SPA fallback - keep this last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for all responses
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "upgrade-insecure-requests"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
